### ISSUE TITLE
v2.0 beta: connection lost

### ISSUE THREAD

**Issue by allbut0ne** [jonpontet/hide-admin-notices#36]
WordPress 6.3 · WP Bakery 7.2:
On a singel page or post backend I got the message "connection lost".
I'm not absolutely sure if this is a conflict with WPB or an other plugin.
However: the message disappears when "hide admin notice" is disabled. 

<img width="736" alt="Bildschirmfoto 2023-11-22 um 09 29 50" src="https://github.com/jonpontet/hide-admin-notices/assets/151764442/88299d9c-e8bf-46a8-9df6-be2fc92b697d">

**Comment by jonpontet** [comment]
Thanks @allbut0ne. It is probably the CSS of Hide Admin Notices that is causing this message, which would otherwise be hidden, to appear. Are you able to supply a copy of the WPB plugin? I dont find it available for download anywhere.

**Comment by allbut0ne** [comment]
I could possibly provide you with access to a WordPress development environment which includes WPB. Would that help?

**Comment by jonpontet** [comment]
Yes that would still be helpful thanks

**Comment by allbut0ne** [comment]
Your access is prepared. How can I contact you?

**Comment by jonpontet** [comment]
***@***.*** please. Thanks! 

Le 26 nov. 2023, 10:14, à 10:14, allbut0ne ***@***.***> a écrit:

**Comment by allbut0ne** [comment]
Sorry, your entry has been censored.

**Comment by jonpontet** [comment]
There is a compatibility issue with notices that have the `hidden` class - as shown here with WP Bakery
<img width="1616" alt="Screenshot 2023-11-27 at 17 38 25" src="https://github.com/jonpontet/hide-admin-notices/assets/20968408/16503027-04d6-49de-81d0-ae6e3a31dad0">

**Comment by jonpontet** [comment]
HI @allbut0ne 
I finally finished a beta release that fixes this issue! 😃 
I completely rewrote the plugin in the end, which is why it's taken some time.
I have tested the beta version on the test site you gave me and all looks good.
Perhaps you can try it out on some other sites and let me know how it is?
You can [download the beta version here](https://pontetlabs.com/hide-admin-notices-beta.zip).
Cheers 🍻

**Comment by jonpontet** [comment]
Resolved in v2.0

**Comment by allbut0ne** [comment]
Yes, seems to work with WPBakery together now. So I'll delete the testing site.
